### ISSUE TITLE
Combine one application for off-chain and credential groups

### ISSUE THREAD

**Issue by 0xjei** [vplasencia/bandada-semaphore-demo#2]
Allow dynamic selection via the user interface between an off-chain group or a credential group. In this way, there is no need to have two deployed applications with related branches, but only one application that includes both functionalities in one branch. This can reduce complexity and increase clarity for the end user.

**Comment by vplasencia** [comment]
Closing this issue because after trying it, the code and logic are a bit more complex and there are some issues since two different groups share the same supabase tables, and that's not good since it's a boilerplate, and should be simple.

Then it's better to keep the code for both off-chain and credential groups but use only one at a time.
