### ISSUE TITLE
Use the latest Semaphore version

### ISSUE THREAD

**Issue by vplasencia** [vplasencia/bandada-semaphore-demo#8]

**Comment by 0xjei** [comment]
This problem is currently blocked by the fact that Bandada supports groups with a tree depth of 16 to 32, whereas Semaphore V4 Beta supports 1 to 12. As a result, there is an error in the proof generation because the artefact corresponding to 16 is not found.

In the [update/v4] branch (https://github.com/bandada-infra/boilerplate/tree/update/v4) you will find the complete update, which can be tested and finalised as soon as Semaphore V4 is released and tree depths >12 are supported.

Please consider this issue as blocked for now.
